# Generated by Django 4.2.6 on 2023-10-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('Customer', 'Пользователь'), ('Manager', 'Менеджер')], default='Customer', max_length=150, verbose_name='Cтатус Пользователя'),
        ),
    ]
