# Generated by Django 4.2.6 on 2023-10-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name1', models.CharField(max_length=30, verbose_name='Имя')),
                ('name2', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('description', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
