# Generated by Django 4.2.6 on 2023-10-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('10S', 'раз в 10 секунд'), ('Daily', 'раз в день,'), ('Weekly', 'раз в неделю'), ('Monthly', 'раз в месяц')], max_length=150, unique=True, verbose_name='периодичность рассылки')),
            ],
            options={
                'verbose_name': 'Периодичность рассылки',
                'verbose_name_plural': 'Периодичности рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100, verbose_name='статус рассылки')),
                ('answer', models.CharField(max_length=150, verbose_name='ответ почтового сервера, если он был')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Содержание письма')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название рассылки')),
                ('begin_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала рассылки')),
                ('close_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата прекращения рассылки')),
                ('satus', models.CharField(choices=[('Finish', 'Завершена'), ('Create', 'Создана'), ('Work', 'Запущена')], default='Create', max_length=150, verbose_name='Cтатус рассылки')),
                ('clients', models.ManyToManyField(to='clients.clients', verbose_name='Список получателей')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.frequencymailing', verbose_name='Периодичность рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Параметры рассылки',
                'verbose_name_plural': 'Виды рассылок',
                'permissions': [('can_change_mailing', 'Can_change_product_active')],
            },
        ),
    ]
