# Generated by Django 4.2.6 on 2023-10-06 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=150, unique=True, verbose_name='периодичность рассылки')),
            ],
            options={
                'verbose_name': 'Периодичность рассылки',
                'verbose_name_plural': 'Периодичности рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('slug', models.TextField(verbose_name='Тема письма')),
            ],
        ),
        migrations.CreateModel(
            name='StatusMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='cтатус')),
            ],
            options={
                'verbose_name': 'Статус рассылки',
                'verbose_name_plural': 'Статусы рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название рассылки')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.frequencymailing', verbose_name='Периодичность рассылки')),
                ('satus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.statusmailing', verbose_name='Cтатус рассылки')),
            ],
            options={
                'verbose_name': 'Периодичность рассылки',
                'verbose_name_plural': 'Периодичности рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime(2023, 10, 6, 20, 7, 27, 765850), verbose_name='Дата и время последней попытки')),
                ('answer', models.CharField(max_length=150, verbose_name='ответ почтового сервера, если он был')),
                ('satus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.statusmailing', verbose_name='статус рассылки')),
            ],
        ),
    ]
