# Generated by Django 4.2.6 on 2023-10-06 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 10, 6, 20, 12, 23, 147738), verbose_name='Дата и время последней попытки'),
        ),
    ]
