# Generated by Django 4.2.6 on 2023-10-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_logs_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='data',
            field=models.DateField(verbose_name='Дата и время последней попытки'),
        ),
    ]
