# Generated by Django 4.2.6 on 2023-10-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_logs_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='slug',
            new_name='content',
        ),
    ]
